blank_issues_enabled: true
contact_links:
  - name: KK VIDEO BOT Support
    url: https://t.me/KanimangalamKovilakam
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://Free_Thinkers.tech/
    about: Documentation for getting started with bot.
